language: python
python:
  - "3.7"
  - "pypy3"
# command to install dependencies
install:
  - pip install tensorflow spacy
  - pip install git+https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
  - git clone https://github.com/interrogator/buzz && cd buzz && python setup.py install && cd ..
  - python setup.py install       
# command to run tests
script:
  - black .
  - flake8 .
  - coverage run -m unittest
