language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install tensorflow spacy
  - python -m spacy download en_core_web_sm
  - git clone https://github.com/interrogator/buzz && cd buzz && python setup.py install && cd ..
  - python setup.py install       
# command to run tests
script:
  - black .
  - flake8 .
  - coverage run -m unittest
