language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - git clone https://github.com/interrogator/buzz && cd buzz && python setup.py install && cd ..
  - python setup.py install       
# command to run tests
script:
  - black .
  - flake8 .
  - coverage run -m unittest
