dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - git clone https://github.com/interrogator/buzz && cd buzz && python setup.py install && cd ..
        - python setup.py install
    - stage: static-checks
      script:
        - flake8 .
        - black .
    - stage: test
      script:  # coverage
        - coverage run -m unittest
        - coverage report
        - codecov
