site_name: buzzword documentation

theme:
    name: readthedocs

nav:
    - User guide: buzzword.md
    - Building corpora: buzzword.md
    - Writing depgrep queries: buzzword.md
    - Running your own buzzword: buzzword.md
    - About: about.md

