site_name: buzzword documentation

theme:
    name: readthedocs

nav:
    - Home: index.md
    - User guide: guide.md
    - Building corpora: building.md
    - Writing depgrep queries: depgrep.md
    - Running your own buzzword: run.md
    - About: about.md
